// Rendering a manual: a command's sections, each the prose a person wrote
// followed by the verbs that share it, and the provenance line that says the
// result was generated. Nothing here writes a file; write.go does that.
package cli

import (
	_ "embed"
	"fmt"
	"strings"
)

// group is one section of a manual: the prose a person wrote for it, and the
// verbs that share that prose, in the order the manual reads them.
type group struct {
	prose string
	paths []string
}

// groups are the manual's sections. Verbs that share a Usage share a section —
// build, wasm, check, run and workerd are all stage's — and each appears once.
func (c Command) groups() []group {
	verbs := c.all()
	var out []group
	at := map[string]int{}
	for _, name := range c.manualOrder(verbs) {
		u := verbs[name].Usage
		i, seen := at[u]
		if !seen {
			at[u] = len(out)
			out = append(out, group{prose: u})
			i = len(out) - 1
		}
		out[i].paths = append(out[i].paths, name)
	}
	return out
}

// sectionFor is the section a verb belongs to: its group's prose and every
// verb that shares it. What someone who typed a verb wrongly needs to see.
func (c Command) sectionFor(verb string) string {
	for _, g := range c.groups() {
		for _, path := range g.paths {
			if path == verb {
				return c.section(g)
			}
		}
	}
	return ""
}

// index is what the binary prints with no verb: every section, flattened,
// because a terminal has no markdown renderer.
func (c Command) index() string {
	var b strings.Builder
	fmt.Fprintf(&b, "%s: every verb. `%s <verb> --help` says what one takes.\n\n", c.Name, c.Name)
	for _, g := range c.groups() {
		b.WriteString(Flatten(c.section(g)))
		b.WriteString("\n")
	}
	return b.String()
}

// section is a group as the manual shows it: the prose a person wrote, then
// the verbs, rendered. The prose says why the group exists; nothing in it
// names a verb or a flag, because those are below it and generated.
func (c Command) section(g group) string {
	prose := strings.TrimRight(g.prose, "\n")
	verbs := Verbs(c.Name, c.all(), g.paths)
	if prose == "" {
		return verbs
	}
	return prose + "\n\n" + verbs
}

// render is the manual: Head, every section, Tail.
func (c Command) render() string {
	var b strings.Builder
	var verbs strings.Builder
	for _, g := range c.groups() {
		verbs.WriteString(strings.TrimRight(c.section(g), "\n") + "\n\n")
	}
	doc := withProvenance(c.Skill, c.Name)
	if !strings.Contains(doc, VerbMarker) {
		// No marker: the verbs go last, which is where they would have gone
		// with nothing said about it.
		return strings.TrimRight(doc, "\n") + "\n\n" + strings.TrimRight(verbs.String(), "\n") + "\n"
	}
	b.WriteString(strings.Replace(doc, VerbMarker+"\n", strings.TrimRight(verbs.String(), "\n")+"\n", 1))
	return b.String()
}

// withProvenance puts a line under a manual's frontmatter saying what wrote
// it and from what. A generated file that does not say it is generated is a
// file someone edits, and the edit is gone at the next build with nothing to
// say it ever happened.
func withProvenance(head, name string) string {
	note := "<!-- Generated by `" + name + " skill` from the verbs and the prose beside them.\n" +
		"     Never edit this file. Signatures come from each verb's Args and Flags,\n" +
		"     the line under one from its Desc, and the prose from a usage.md\n" +
		"     and the skill.md beside the command. `go test` fails when this\n" +
		"     copy is stale. -->\n\n"
	lines := strings.SplitN(head, "---\n", 3)
	if len(lines) == 3 && strings.TrimSpace(lines[0]) == "" {
		return "---\n" + lines[1] + "---\n\n" + note + strings.TrimLeft(lines[2], "\n")
	}
	return note + head
}
